//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareArea", ReplyAction="*")]
        float SquareArea(float length, float width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareArea", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SquareAreaAsync(float length, float width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RectangleArea", ReplyAction="*")]
        float RectangleArea(float length, float width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RectangleArea", ReplyAction="*")]
        System.Threading.Tasks.Task<float> RectangleAreaAsync(float length, float width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TriangleArea", ReplyAction="*")]
        float TriangleArea(float Base, float Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TriangleArea", ReplyAction="*")]
        System.Threading.Tasks.Task<float> TriangleAreaAsync(float Base, float Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CircleArea", ReplyAction="*")]
        float CircleArea(float radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CircleArea", ReplyAction="*")]
        System.Threading.Tasks.Task<float> CircleAreaAsync(float radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap>, CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float SquareArea(float length, float width) {
            return base.Channel.SquareArea(length, width);
        }
        
        public System.Threading.Tasks.Task<float> SquareAreaAsync(float length, float width) {
            return base.Channel.SquareAreaAsync(length, width);
        }
        
        public float RectangleArea(float length, float width) {
            return base.Channel.RectangleArea(length, width);
        }
        
        public System.Threading.Tasks.Task<float> RectangleAreaAsync(float length, float width) {
            return base.Channel.RectangleAreaAsync(length, width);
        }
        
        public float TriangleArea(float Base, float Height) {
            return base.Channel.TriangleArea(Base, Height);
        }
        
        public System.Threading.Tasks.Task<float> TriangleAreaAsync(float Base, float Height) {
            return base.Channel.TriangleAreaAsync(Base, Height);
        }
        
        public float CircleArea(float radius) {
            return base.Channel.CircleArea(radius);
        }
        
        public System.Threading.Tasks.Task<float> CircleAreaAsync(float radius) {
            return base.Channel.CircleAreaAsync(radius);
        }
    }
}
